general:
  kafka-topic: trader-updates

spring:
  kafka:
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.jpmc.midascore.foundation"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 33400